### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by mikejnpc** [mutalisk999/btc_wallet_dump_tool#3]
how do you init the process?

**Comment by mutalisk999** [comment]
If you just want to decrypt wallet.dat and dump the private keys, you can:

```
file_name = 'C:/btc_data/wallet.dat'       # path of btc wallet data file 
wallet_pass = 'my_password'                # wallet password and use empty string if no password
btc_wallet.dump_private_key_from_wallet_db(file_name, wallet_pass)
```

**Comment by mutalisk999** [comment]
Checkout the readme file updated and use the second way to export the private keys (Command Line).

**Comment by Danyalkasiri** [comment]
> Text that is a quote

**Comment by Danyalkasiri** [comment]
#1

**Comment by Danyalkasiri** [comment]
file_name = 'C:/btc_data/wallet.dat'       # path of btc wallet data file 
wallet_pass = 'my_password'                # wallet password and use empty string if no password
btc_wallet.dump_private_key_from_wallet_db(file_name, wallet_pass)

**Comment by Danyalkasiri** [comment]
@mutalisk999 #1 
تکراری از #
/
